# Default values for customer-api
replicaCount: 1

image:
  repository: "760347630853.dkr.ecr.us-east-1.amazonaws.com/customer-api"
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::760347630853:role/customer-api-service-role"
  name: "customer-api-service-account"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /customers
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    # API should handle /api/* paths, frontend gets root
    alb.ingress.kubernetes.io/group.name: customer-app
    alb.ingress.kubernetes.io/group.order: '200'
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix
        - path: /customers
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Application configuration
config:
  awsRegion: "us-east-1"
  tableName: "Customers"
  port: "8080"
  dynamodbEndpoint: "https://dynamodb.us-east-1.amazonaws.com"

# Health checks
healthCheck:
  enabled: true
  path: "/health"
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

readinessCheck:
  enabled: true
  path: "/customers"
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3