apiVersion: v2
name: customer-management
description: Complete Customer Management System - Frontend and Backend
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - customer
  - management
  - fullstack
  - react
  - golang
home: https://github.com/emiteze/tcc-ufu
maintainers:
  - name: TCC UFU Team
    email: contact@example.com
dependencies:
  - name: customer-api
    version: "0.1.0"
    repository: "file://../customer-api"
  - name: customer-frontend
    version: "0.1.0" 
    repository: "file://../customer-frontend"