{{- if .Values.istio.enabled }}
{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "customer-api.fullname" . }}-destination-rule
  labels:
    {{- include "customer-api.labels" . | nindent 4 }}
spec:
  host: {{ include "customer-api.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- with .Values.istio.destinationRule.trafficPolicy }}
  trafficPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}