apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "customer-api.fullname" . }}-gateway
  namespace: istio-ingress
  labels:
    {{- include "customer-api.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  {{- if .Values.gateway.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.gateway.tls.secretName }}
    hosts:
    - "*"
  {{- end }}